global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'payment_service'
    static_configs:
      - targets: ['payment_service:80']

  - job_name: 'notification_service'
    static_configs:
      - targets: ['notification_service:80']